### ISSUE TITLE
"Add class" adds a <Compile Remove="Classname"/> item to csproj

### ISSUE THREAD

**Issue by lennartb-** [onovotny/MSBuildSdkExtras#108]
Repro:

1. Add class to .Net Core-style project via right click on a folder (e.g. "SomeFolder") node in Solution Explorer "Add" => "New class"
2. Save all files (Ctrl-Shift-S)
3. The following gets added to the csproj:

`
 <ItemGroup>
    <Compile Remove="SomeFolder\Class1.cs" />
  </ItemGroup>
`

Expected:
Nothing gets added to the csproj

Env:
VS 15.8.2
MSBuild.Sdk.Extras/1.6.47
TargetFramework net461
```
 <ProjectTypeGuids>
{60dc8134-eba5-43b8-bcc9-bb4bc16c2548};
{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}
</ProjectTypeGuids>
```

We can reproduce this on multiple machines and narrowed it down to projects with MsBuildSdkExtras as SDK, this doesn't happen with Microsoft.NET.Sdk.

The problem here is that it appears that the class has been added to the project, but is excluded immediately by the csproj which leads to VS not recognizing the class. Happy to provide more info if needed.

**Comment by onovotny** [comment]
Fixed in the next Extras after 1.6.47, making its way to NuGet shortly.

**Comment by hydnar** [comment]
I believe this is still an issue in v2.0.24 and 2.0.29.
Visual Studio 2017 - 15.9.12
Here is the content of my .csproj, repro steps are the same:
<Project Sdk="MSBuild.Sdk.Extras/2.0.29">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;Xamarin.iOS10;MonoAndroid90;</TargetFrameworks>
    <NeutralLanguage>en-NZ</NeutralLanguage>
    <LangVersion>default</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**\*.shared.cs" />
  </ItemGroup>
  <ItemGroup Condition=" $(TargetFramework.StartsWith('netstandard')) ">
    <Compile Include="**\*.netstandard.cs" />
  </ItemGroup>
  <ItemGroup Condition=" $(TargetFramework.StartsWith('uap10.0')) ">
    <Compile Include="**\*.uwp.cs" />
  </ItemGroup>
  <ItemGroup Condition=" $(TargetFramework.StartsWith('MonoAndroid')) ">
    <Compile Include="**\*.android.cs" />
    <Compile Include="**\Android\**\*.cs" />
  </ItemGroup>
  <ItemGroup Condition=" $(TargetFramework.StartsWith('Xamarin.iOS')) ">
    <Compile Include="**\*.ios.cs" />
    <Compile Include="**\iOS\**\*.cs" />
  </ItemGroup>

  <ItemGroup Condition=" $(TargetFramework.StartsWith('net4')) ">
    <Compile Include="**\*.net.cs" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'MonoAndroid90'">
    <PackageReference Include="Xamarin.Android.Support.v7.AppCompat">
      <Version>28.0.0.1</Version>
    </PackageReference>
  </ItemGroup>

  <Import Project="$(MSBuildSDKExtrasTargets)" Condition="Exists('$(MSBuildSDKExtrasTargets)')" />

</Project>
